Ais\PertemuanDosenBundle\Entity\PertemuanDosen:
 type: entity
 table: pertemuan_dosen
 id:
  id: 
   type: integer
   generator: { strategy: AUTO }
 fields:
  pertemuan_id:
   type: integer
  dosen_id:
   type: integer
  kehadiran:
   type: integer
   length: 2
  keterangan:
   type: text
  is_delete:
   type: boolean
   nullable: true
