# src/Ais/PertemuanDosenBundle/Resources/config/validation.yml
Ais\PertemuanDosenBundle\Entity\PertemuanDosen:
    properties:
        pertemuan_id:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 2
                max: 100
                minMessage: "Your title must be at least {{ limit }} characters length"
                maxMessage: "Your title name cannot be longer than {{ limit }} characters length"
