<?php

namespace Ais\PertemuanDosenBundle\Repository;

/**
 * PertemuanDosenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PertemuanDosenRepository extends \Doctrine\ORM\EntityRepository
{
}
